classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.tide_gauge.readers.TideGaugeReader

coords:
  time:
    .*:
      name: time
      data_converters:
        - classname: tsdat.io.converters.StringToDatetime
          format: "%Y-%m-%d %H:%M:%S"
          timezone: UTC

data_vars:
  water_level:
    .*:
      name: water_level