classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.ctd.readers.CTDReader

coords:
  time:
    .*:
      name: time
      data_converters:
        - classname: tsdat.io.converters.StringToDatetime
          format: "%Y-%m-%d %H:%M:%S.%f"
          timezone: UTC

data_vars:
  temp:
    name: temp
  do:
    name: do

  salinity:
    name: salinity
