attrs:
  # https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html
  # https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3
  # Dataset Description
  conventions: "CD-1.6, ACDD-1.3, IOOS-1.2"
  featureType: timeseries
  id: MCRLdata_PAR
  infoURL: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  naming_authority: gov.pnnl.sequim
  standard_name_vocabulary: CF Standard Name Table v79
  title: MCRLdata at PNNL-Sequim - PAR
  description: >-
    Two Li-COR Li-193 Spherical Underwater Quantum sensors were deployed on piles of the
    Marine and Coastal Research Laboratory (MCRL) pier at the Pacific Northwest National
    Laboratory (PNNL) campus in Sequim, Washington. These instruments measure
    photosythetic photon flux density (PPFD, umol m-2 s-1), which is important for
    biogeochemistry processes in the marine environment. This deployment is part of the
    MCRLdata project to establish long-term marine monitoring at the PNNL-Sequim Campus.
  keywords: Sequim, data, marine, photosythetically active radiation, par
  # Attribution
  creator_country: USA
  creator_email: mcrldata at pnnl.gov
  creator_institution: Pacific Northwest National Laboratory (PNNL) - Sequim
  creator_institution_url: https://www.pnnl.gov/
  creator_sector: other
  creator_type: institution
  creator_url: https://www.pnnl.gov/
  institution: Pacific Northwest National Laboratory (PNNL)
  publisher_country: USA
  publisher_email: mcrldata at pnnl.gov
  publisher_institution: Pacific Northwest National Laboratory (PNNL) - Sequim
  publisher_url: https://www.pnnl.gov/

  # Platform and Instrument
  platform: pier
  platform_name: mcrl_pier
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  instrument: In Situ/Laboratory Instruments > Photon/Optical Detectors > PAR Sensors
  instrument_vocabulary: GCMD Instrument Keywords #https://gcmd.earthdata.nasa.gov/KeywordViewer/
  make_model: Li-COR Li-193 Sepherical Underwater Quantum Sensor

  # Geospatial and Time
  geospatial_bounds: POINT(48.07922 -123.04512)
  geospatial_bounds_crs: "EPSG:4326"
  time_coverage_start: "2021-04-07"
  time_coverage_resolution: "15:00"

  # Don't delete these... they will be important for secondary pipelines
  location_id: par
  dataset_name: mcrl_pier
  qualifier: licor_li193_1
  temporal: 15min
  data_level: a1

coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      long_name: Time (UTC)
      standard_name: time
      units: seconds since 1970-01-01 00:00:00
      cf_role: timeseries_id
      coverage_content_type: coordinate
      timezone: UTC

data_vars:
  lower_par:
    dims: [time]
    dtype: float
    attrs:
      long_name: Lower Photosynthetically Active Radiation (PAR) Sensor
      standard_name: downwelling_photon_flux_in_sea_water
      units: umol m-2 s-1
      coverage_content_type: physicalMeasurement
      description:
        "PAR flux density measured by the Li-COR 193 quantum sensor, lower sensor under
        sea water"
      fail_min: 0
      fail_max: 500
      calibration_date: "2021-02-04"

  upper_par:
    dims: [time]
    dtype: float
    attrs:
      long_name: Upper Photosynthetically Active Radiation (PAR) Sensor
      standard_name: downwelling_photon_flux_in_sea_water
      units: umol m-2 s-1
      coverage_content_type: physicalMeasurement
      description:
        "PAR flux density measured by the Li-COR 193 quantum sensor, upper sensor under
        sea water"
      fail_min: 0
      fail_max: 500
      calibration_date: "2021-01-14"
