attrs:
  # https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html
  # https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3
  # Dataset Description
  conventions: "CD-1.6, ACDD-1.3, IOOS-1.2"
  featureType: timeseries
  id: MCRLdata_pH
  infoURL: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  naming_authority: gov.pnnl.sequim
  standard_name_vocabulary: CF Standard Name Table v79
  title: MCRLdata at PNNL-Sequim - pH
  description: >-
    An Onset mx2501 was attached to a steel cage suspended into the water below a
    floating dock that is attached to the Marine and Coastal Research Laboratory (MCRL)
    pier at the Pacific Northwest National Laboratory (PNNL) campus in Sequim,
    Washington. This instrument measures the potential of hydrogen (pH), which this
    parameter directly impacts organisms and habitats in the ocean. This deployment is
    part of the MCRLdata project to establish long-term marine monitoring at the
    PNNL-Sequim Campus.
  keywords: Sequim, data, marine, pH, acidity
  # Attribution
  creator_country: USA
  creator_email: mcrldata at pnnl.gov
  creator_institution: Pacific Northwest National Laboratory (PNNL) - Sequim
  creator_institution_url: https://www.pnnl.gov/
  creator_sector: other
  creator_type: institution
  creator_url: https://www.pnnl.gov/
  institution: Pacific Northwest National Laboratory (PNNL)
  publisher_country: USA
  publisher_email: mcrldata at pnnl.gov
  publisher_institution: Pacific Northwest National Laboratory (PNNL) - Sequim
  publisher_url: https://www.pnnl.gov/

  # Platform and Instrument
  platform: dock
  platform_name: mcrl_dock
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  instrument: In Situ/Laboratory Instruments > Chemical Meters/Analyzers > pH Meters
  instrument_vocabulary: GCMD Instrument Keywords #https://gcmd.earthdata.nasa.gov/KeywordViewer/
  make_model: Onset
  calibration_date: "2021-09-12"

  # Geospatial and Time
  geospatial_bounds: POINT(48.07927 -123.04506)
  geospatial_bounds_crs: "EPSG:4326"
  time_coverage_start: "2021-08-13"
  time_coverage_end: "2021-09-12"
  time_coverage_resolution: "5:00"

  # Don't delete these... they will be important for secondary pipelines
  location_id: ph_ #TODO: currently requiring 3 characters
  dataset_name: mcrl_pier
  qualifier: onset_mx2501_1
  temporal: 5min
  data_level: a1

coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      long_name: Time (UTC)
      standard_name: time
      units: seconds since 1970-01-01 00:00:00
      cf_role: timeseries_id
      coverage_content_type: coordinate
      timezone: UTC

data_vars:
  temperature:
    dims: [time]
    dtype: float
    attrs:
      long_name: Water Temperature (degC)
      standard_name: temperature_of_analysis_of_sea_water
      units: degree_C
      coverage_content_type: physicalMeasurement
      description: "Ambient water temperature in the vicinity of the device"
      fail_min: 0
      fail_max: 30

  pH:
    dims: [time]
    dtype: float
    attrs:
      long_name: pH
      standard_name: sea_water_ph_reported_on_total_scale
      units: unitless
      coverage_content_type: physicalMeasurement
      description: "Measure of acidity of seawater"
      fail_min: 0
      fail_max: 14
