classname: pipelines.ph.pipeline.PH

triggers:
  - .*ph_.*\.txt

retriever:
  path: pipelines/ph/config/retriever.yaml

dataset:
  path: pipelines/ph/config/dataset.yaml

quality:
  path: shared/quality.yaml

storage:
  path: shared/storage.yaml
  overrides:
    /parameters/storage_root: storage/ph
