classname: pipelines.ph.pipeline.PH

triggers:
  - .*SAMI.*\.txt

retriever:
  path: pipelines/ph/config/retriever.yaml

dataset:
  path: pipelines/ph/config/dataset_isami.yaml

quality:
  path: shared/quality.yaml

storage:
  path: shared/storage.yaml
