classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*ph_.*\.txt:
    classname: pipelines.ph.readers.OnsetReader
  .*SAMI.*\.txt:
    classname: pipelines.ph.readers.SamiReader

coords:
  time:
    .*:
      name: time
      data_converters:
        - classname: tsdat.io.converters.StringToDatetime
          format: "%Y-%m-%d %H:%M:%S"
          timezone: UTC

data_vars:
  temperature:
    .*:
      name: temperature

  pH:
    .*:
      name: pH

  salinity:
    .*SAMI.*:
      name: SalinityConst
