classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*ph_.*\.txt:
    classname: pipelines.ph.readers.OnsetReader
  .*SAMI.*\.txt:
    classname: pipelines.ph.readers.SamiReader

coords:
  time:
    .*:
      name: time
      data_converters:
        - classname: tsdat.io.converters.StringToDatetime
          format: "%Y-%m-%d %H:%M:%S"
          timezone: UTC

data_vars:
  temperature:
    .*ph_.*\.txt:
      name: temperature
    .*SAMI.*\.txt:
      name: Temperature C

  pH:
    .*ph_.*\.txt:
      name: pH
    .*SAMI.*\.txt:
      name: pHConstSal

  salinity:
    .*SAMI.*\.txt:
      name: SalinityConst
