classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.ph.readers.PHReader

coords:
  time:
    .*:
      name: time
      data_converters:
        - classname: tsdat.io.converters.StringToDatetime
          format: "%Y-%m-%d %H:%M:%S"
          timezone: UTC

data_vars:
  temperature:
    .*:
      name: temperature
      
  pH:
    .*:
      name: pH