classname: tsdat.io.storage.FileSystem
parameters:
  storage_root: storage/ph
  data_folder: netcdf
  data_storage_path: "{storage_root}/{datastream}/{data_folder}/{year}/{month}/{day}"
  ancillary_storage_path: "{storage_root}/{datastream}/{ancillary_folder}/{year}/{month}/{day}"
handler:
  classname: tsdat.io.handlers.NetCDFHandler
