attrs:
  # https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html
  # https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3
  # Dataset Description
  conventions: "CD-1.6, ACDD-1.3, IOOS-1.2"
  featureType: timeseries
  id: MCRLdata_adcp
  infoURL: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  naming_authority: gov.pnnl.sequim
  standard_name_vocabulary: CF Standard Name Table v79
  title: MCRLdata at PNNL-Sequim - ADCP
  # TODO: Change to "Summary" to meet standards
  description: "A Nortek 400kHz 2D Horizontal Profiler was installed on the Marine and Coastal 
  Research Laboratory (MCRL) pier at the Pacific Northwest National Laboratory (PNNL) campus 
  in Sequim, Washington. This instrument is located 5 meters above the seabed, facing true 
  East and has an actual range of 98 meters because of the bathymetry, measuring each second 
  for a 5-minute interval every 15 minutes with a bin size of 4 meters. This Acoustic Doppler 
  Current Profiler (ADCP) measures horizontal flow velocity, which helps to characterize the 
  tidal cycle and flow exchange, which impacts nutrient and pollutant flushing rates. This 
  deployment is part of the MCRLdata project to establish long-term marine monitoring at the 
  PNNL-Sequim Campus."
  keywords: Sequim, data, marine, channel, water velocity, water direction, flows
  
  # Attribution
  creator_country: USA
  creator_email: mcrldata at pnnl.gov
  creator_institution: Pacific Northwest National Laboratory (PNNL) - Sequim
  creator_institution_url: https://www.pnnl.gov/
  creator_sector: other
  creator_type: institution
  creator_url: https://www.pnnl.gov/
  institution: Pacific Northwest National Laboratory (PNNL)
  publisher_country: USA
  publisher_email: mcrldata at pnnl.gov
  publisher_institution: Pacific Northwest National Laboratory (PNNL) - Sequim
  publisher_url: https://www.pnnl.gov/
  
  # Platform and Instrument
  platform: pier
  platform_name: mcrl_pier
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  instrument: In Situ/Laboratory Instruments > Current/Wind Meters > Current Meters
  instrument_vocabulary: GCMD Instrument Keywords #https://gcmd.earthdata.nasa.gov/KeywordViewer/
  make_model: Nortek 400kHz 2D Horizontal Profiler
  
  # Geospatial and Time
  geospatial_bounds: POINT(48.07924 -123.04506)
  geospatial_bounds_crs: "EPSG:4326"
  time_coverage_start: "2021-09-08"
  time_coverage_resolution: "15:00"

  # TODO: Can we delete these? Part of storage location and file name right now...
  location_id: adcp
  dataset_name: mcrl_pier
  data_level: a1
  qualifier: nortek_awac_1
  temporal: 5min
  
  #TODO: Do we want sampling_interval?

coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      long_name: Time (UTC)
      standard_name: time
      units: seconds since 1970-01-01 00:00:00
      cf_role: timeseries_id
      coverage_content_type: coordinate
      timezone: UTC
  range:
    dims: [range]
    dtype: float32
    attrs:
      long_name: Range
      units: m
      coverage_content_type: coordinate
  dir: # How does this differ from U_dir?
    dims: [dir]
    dtype: str
    attrs:
      long_name: Direction
      units: "1"
      cf_role: timeseries_id
      coverage_content_type: coordinate
  beam:
    dims: [beam]
    dtype: int
    attrs:
      long_name: Beam Number
      units: "1"
      coverage_content_type: coordinate

data_vars:
  vel:
    dims: [dir, range, time]
    dtype: float32
    attrs:
      long_name: Velocity
      standard_name: water_velocity
      units: m/s
      coverage_content_type: physicalMeasurement
      fail_min: -5
      fail_max: 5
  U_mag:
    dims: [range, time]
    dtype: float32
    attrs:
      long_name: Flow Speed
      standard_name: sea_water_velocity_magnitude
      units: m s-1
      coverage_content_type: physicalMeasurement
      fail_min: 0
      fail_max: 5
  U_dir:
    dims: [range, time]
    dtype: float32
    attrs:
      long_name: Flow Direction
      standard_name: sea_water_velocity_to_direction
      units: degree
      coverage_content_type: physicalMeasurement
      fail_min: -180
      fail_max: 180
  amplitude:
    dims: [beam, range, time]
    dtype: int
    attrs:
      long_name: Amplitude
      standard_name: amplitude
      units: count
      coverage_content_type: physicalMeasurement
  temperature:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Transducer Temperature of ADCP Measurement (degC)
      standard_name: sea_water_temperature
      units: degree_C
      coverage_content_type: physicalMeasurement
      fail_min: 0
      fail_max: 30
  depth:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Depth of ADCP Measurement (m)
      standard_name: depth
      units: m
      coverage_content_type: coordinate
      axis: Z
      positive: down
      fail_min: 0
      fail_max: 1000
  heading:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Heading of ADCP Measurement (deg)
      standard_name: platform_course
      units: degree
      coverage_content_type: physicalMeasurement
      fail_min: 0
      fail_max: 360
  pitch:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Pitch of ADCP Measurement (deg)
      standard_name: platform_pitch
      units: degree
      coverage_content_type: physicalMeasurement
      fail_min: 0
      fail_max: 360
  roll:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Roll of ADCP Measurement (deg)
      standard_name: platform_roll
      units: degree
      coverage_content_type: physicalMeasurement
      fail_min: 0
      fail_max: 360
  c_sound: #TODO: Remove?
    dims: [time]
    dtype: float32
    attrs:
      long_name: Speed of Sound (m/s)
      standard_name: speed_of_sound_in_sea_water
      units: m s-1
  pressure:
    dims: [time]
    dtype: float32
    attrs:
      long_name: Pressure (dBar)
      standard_name: sea_water_pressure
      units: dbar
      coverage_content_type: physicalMeasurement
      fail_min: 0
      fail_max: 1000
