classname: tsdat.io.retrievers.StorageRetriever
parameters:
  transformation_parameters:
    # Where the point lies in the coordinate bounds (CENTER, LEFT, RIGHT)
    alignment:
      time: LEFT

    # How far to look for the next available data point
    ## In native units of seconds, or use int + numpy.timedelta64 units
    range:
      time: 900

    # Width of the transformation
    ## In native units of seconds
    width:
      time: 600

coords:
  time:
    # .*tide_gauge.*:
    #   name: time
    name: N/A # create a new time grid
    data_converters:
      - classname: tsdat.transform.CreateTimeGrid
        interval: 5min

data_vars:
  water_level:
    .*tide_gauge.*:
      name: water_level
      data_converters:
        - classname: tsdat.transform.Interpolate

  temp:
    .*ctd.*:
      name: temp
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
  do:
    .*ctd.*:
      name: do
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
  salinity:
    .*ctd.*:
      name: salinity
      data_converters:
        - classname: tsdat.transform.NearestNeighbor

  cdom:
    .*cdom.*:
      name: cdom
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
  phycoerythrin:
    .*cdom.*:
      name: phycoerythrin
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
  chlorophyll:
    .*cdom.*:
      name: chlorophyll
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
