classname: tsdat.io.retrievers.StorageRetriever
parameters:
  transformation_parameters:
    # Where the point lies in the coordinate bounds (CENTER, LEFT, RIGHT)
    alignment:
      time: CENTER

    # How far to look for the next available data point
    ## In native units of seconds, or use int + numpy.timedelta64 units
    range:
      time: 150

    # Width of the transformation
    ## In native units of seconds
    width:
      time: 60

coords:
  time:
    name: N/A # create a new time grid
    data_converters:
      - classname: tsdat.transform.CreateTimeGrid
        interval: 5min
  # range:
  #   .*adcp.*:
  #     name: range

data_vars:
  water_level:
    .*tide_gauge.*:
      name: water_level
      data_converters:
        - classname: tsdat.transform.NearestNeighbor

  # qc_U_mag:
  #   .*adcp.*:
  #     name: qc_U_mag
  #     data_converters:
  #       - classname: pipelines.data_fusion.converters.DimensionTranspose
  # U_mag:
  #   .*adcp.*:
  #     name: U_mag
  #     data_converters:
  #       - classname: pipelines.data_fusion.converters.DimensionTranspose
  #       - classname: tsdat.transform.NearestNeighbor

  # qc_U_dir:
  #   .*adcp.*:
  #     name: qc_U_dir
  #     data_converters:
  #       - classname: pipelines.data_fusion.converters.DimensionTranspose
  # U_dir:
  #   .*adcp.*:
  #     name: U_dir
  #     data_converters:
  #       - classname: pipelines.data_fusion.converters.DimensionTranspose
  #       - classname: tsdat.transform.NearestNeighbor

  temp:
    .*ctd.*:
      name: temp
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
  do:
    .*ctd.*:
      name: do
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
  salinity:
    .*ctd.*:
      name: salinity
      data_converters:
        - classname: tsdat.transform.NearestNeighbor

  # cdom:
  #   .*cdom.*:
  #     name: cdom
  #     data_converters:
  #       - classname: tsdat.transform.NearestNeighbor

  # phycoerythrin:
  #   .*cdom.*:
  #     name: phycoerythrin
  #     data_converters:
  #       - classname: tsdat.transform.NearestNeighbor

  # chlorophyll:
  #   .*cdom.*:
  #     name: chlorophyll
  #     data_converters:
  #       - classname: tsdat.transform.NearestNeighbor

  SPL:
    .*hydrophone.*:
      name: SPL
      data_converters:
        - classname: tsdat.transform.NearestNeighbor
