
storage:
  classname:  tsdat.io.FilesystemStorage
  parameters:
    retain_input_files: False
    root_dir: /data/storage

  file_handlers:
    input:
      sta:
        file_pattern: '.*\.sta'
        classname: tsdat.io.filehandlers.CsvHandler
        parameters:
          read:
            read_csv:
              sep: "\t"
              header: 41
              index_col: False

    output:
      netcdf:
        file_extension: '.nc'
        classname: tsdat.io.filehandlers.NetCdfHandler
