classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: tsdat.NetCDFReader

coords:
  time:
    name: time
    data_converters:
      - classname: tsdat.io.converters.StringToDatetime
        format: "%Y-%m-%d %H:%M:%S"
        timezone: UTC
  position:
    name: position
  sample:
    name: sample

data_vars:
  pco2_raw:
    name: co2
  o2_raw:
    name: o2
  zero_coeff:
    name: zero_coeff
  span_coeff:
    name: span_coeff
  flag:
    name: flag
  minute:
    name: minute
  pressure:
    name: pres
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: kPa
  temp_licor:
    name: li_temp
  rh:
    name: rh
  temp_rh:
    name: rh_temp
