attrs:
  # https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html
  # https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3
  # Dataset Description
  conventions: "CD-1.6, ACDD-1.3, IOOS-1.2"
  featureType: timeseries
  id: MCRLdata_cdom
  infoURL: https://www.osti.gov/biblio/1842840
  license: Freely Distributed
  naming_authority: gov.pnnl.sequim
  standard_name_vocabulary: CF Standard Name Table v79
  title: MCRLdata at PNNL-Sequim - CDOM
  description: >-
    A Seabird ECO Triplet sensor was attached to a steel cage suspended into the water
    below a floating dock that is attached to the Marine and Coastal Research Laboratory
     (MCRL) pier at the Pacific Northwest National Laboratory (PNNL) campus in Sequim,
    Washington. This instrument measures CDOM, chlorophyll, and phycoerythrin, which are
    important water quality measurements. This deployment is part of the MCRLdata
    project to establish long-term marine monitoring at the PNNL-Sequim Campus.
  keywords: Sequim, data, marine, cdom, chlorophyll, phycoerythrin
  # Attribution
  creator_country: USA
  creator_email: mcrldata at pnnl.gov
  creator_institution: Pacific Northwest National Laboratory (PNNL) - Sequim
  creator_institution_url: https://www.pnnl.gov/
  creator_sector: other
  creator_type: institution
  creator_url: https://www.pnnl.gov/
  institution: Pacific Northwest National Laboratory (PNNL)
  publisher_country: USA
  publisher_email: mcrldata at pnnl.gov
  publisher_institution: Pacific Northwest National Laboratory (PNNL) - Sequim
  publisher_url: https://www.pnnl.gov/

  # Platform and Instrument
  platform: dock
  platform_name: mcrl_dock
  platform_vocabulary: https://mmisw.org/ont/ioos/platform
  instrument: In Situ/Laboratory Instruments > Chemical Meters/Analyzers > Fluorometers
  instrument_vocabulary: GCMD Instrument Keywords #https://gcmd.earthdata.nasa.gov/KeywordViewer/
  make_model: Seabird ECO Triplet-w FL3WB
  calibration_date: "2018-09-19"

  # Geospatial and Time
  geospatial_bounds: POINT(48.07927 -123.04506)
  geospatial_bounds_crs: "EPSG:4326"
  time_coverage_start: "2021-08-05"
  time_coverage_resolution: "5:00"

  # Don't delete these... they will be important for secondary pipelines
  location_id: cdom
  dataset_name: mcrl_pier
  qualifier: seabird_smp_1
  temporal: 5min
  data_level: a1

coords:
  time:
    dims: [time]
    dtype: datetime64[ms]
    attrs:
      long_name: Time (UTC)
      standard_name: time
      units: seconds since 1970-01-01 00:00:00
      cf_role: timeseries_id
      coverage_content_type: coordinate
      timezone: UTC

data_vars:
  cdom:
    dims: [time]
    dtype: float
    attrs:
      long_name: Colored Dissolved Organic Matter - CDOM (ppb)
      standard_name: concentration_of_colored_dissolved_organic_matter_in_sea_water_expressed_as_equivalent_mass_fraction_of_quinine_sulfate_dihydrate
      units: "1"
      description: >-
        CDOM - colored dissolved organic matter occurs naturally in aquatic environments
        primarily as a result of tannins released from decaying plant and animal matter,
        which can enter coastal areas in river run-off containing organic materials
        leached from soils. When present in high concentrations, it imparts a brown or
        yellowish color to water. Its presence can negatively impact fish populations by
        reducing dissolved oxygen concentrations to harmful levels and by releasing
        nutrients and metals that contaminate the water.
      fail_min: 0
      fail_max: 150

  phycoerythrin:
    dims: [time]
    dtype: float
    attrs:
      long_name: Phycoerythrin (ppb)
      standard_name: phycoerythrin
      units: "1"
      coverage_content_type: physicalMeasurement
      description: >-
        Phycoerythrin is a red protein-pigment complex from the light-harvesting
        phycobiliprotein family, present in red algae and cryptophytes, accessory to the
        main chlorophyll pigments responsible for photosynthesis.
      fail_min: 0
      fail_max: 100

  chlorophyll:
    dims: [time]
    dtype: float
    attrs:
      long_name: chlorophyll (ug/L)
      standard_name: mass_concentration_of_chlorophyll_in_sea_water
      units: ug L-1
      coverage_content_type: physicalMeasurement
      description: >-
        Chlorophylls are the green pigments found in most plants, algae and
        cyanobacteria; their presence is essential for photosynthesis to take place.
      fail_min: 0
      fail_max: 100
