classname: pipelines.cdom.pipeline.CDOM

triggers:
  - .*cdom.*\.log

retriever:
  path: pipelines/cdom/config/retriever.yaml

dataset:
  path: pipelines/cdom/config/dataset.yaml

quality:
  path: shared/quality.yaml

storage:
  path: shared/storage.yaml
  overrides:
    /parameters/storage_root: storage/cdom
